# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mchonaker/projects/playhouse/Face-Tracking-Projection-Mapping

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mchonaker/projects/playhouse/Face-Tracking-Projection-Mapping

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mchonaker/projects/playhouse/Face-Tracking-Projection-Mapping/CMakeFiles /home/mchonaker/projects/playhouse/Face-Tracking-Projection-Mapping//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mchonaker/projects/playhouse/Face-Tracking-Projection-Mapping/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/tests/OpenCVFaceTrack

# Build rule for target.
bin/tests/OpenCVFaceTrack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bin/tests/OpenCVFaceTrack
.PHONY : bin/tests/OpenCVFaceTrack

# fast build rule for target.
bin/tests/OpenCVFaceTrack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVFaceTrack.dir/build.make CMakeFiles/bin/tests/OpenCVFaceTrack.dir/build
.PHONY : bin/tests/OpenCVFaceTrack/fast

#=============================================================================
# Target rules for targets named bin/tests/OpenCVInc

# Build rule for target.
bin/tests/OpenCVInc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bin/tests/OpenCVInc
.PHONY : bin/tests/OpenCVInc

# fast build rule for target.
bin/tests/OpenCVInc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVInc.dir/build.make CMakeFiles/bin/tests/OpenCVInc.dir/build
.PHONY : bin/tests/OpenCVInc/fast

src/tests/opencv_facetrack.o: src/tests/opencv_facetrack.cpp.o

.PHONY : src/tests/opencv_facetrack.o

# target to build an object file
src/tests/opencv_facetrack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVFaceTrack.dir/build.make CMakeFiles/bin/tests/OpenCVFaceTrack.dir/src/tests/opencv_facetrack.cpp.o
.PHONY : src/tests/opencv_facetrack.cpp.o

src/tests/opencv_facetrack.i: src/tests/opencv_facetrack.cpp.i

.PHONY : src/tests/opencv_facetrack.i

# target to preprocess a source file
src/tests/opencv_facetrack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVFaceTrack.dir/build.make CMakeFiles/bin/tests/OpenCVFaceTrack.dir/src/tests/opencv_facetrack.cpp.i
.PHONY : src/tests/opencv_facetrack.cpp.i

src/tests/opencv_facetrack.s: src/tests/opencv_facetrack.cpp.s

.PHONY : src/tests/opencv_facetrack.s

# target to generate assembly for a file
src/tests/opencv_facetrack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVFaceTrack.dir/build.make CMakeFiles/bin/tests/OpenCVFaceTrack.dir/src/tests/opencv_facetrack.cpp.s
.PHONY : src/tests/opencv_facetrack.cpp.s

src/tests/opencv_inc.o: src/tests/opencv_inc.cpp.o

.PHONY : src/tests/opencv_inc.o

# target to build an object file
src/tests/opencv_inc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVInc.dir/build.make CMakeFiles/bin/tests/OpenCVInc.dir/src/tests/opencv_inc.cpp.o
.PHONY : src/tests/opencv_inc.cpp.o

src/tests/opencv_inc.i: src/tests/opencv_inc.cpp.i

.PHONY : src/tests/opencv_inc.i

# target to preprocess a source file
src/tests/opencv_inc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVInc.dir/build.make CMakeFiles/bin/tests/OpenCVInc.dir/src/tests/opencv_inc.cpp.i
.PHONY : src/tests/opencv_inc.cpp.i

src/tests/opencv_inc.s: src/tests/opencv_inc.cpp.s

.PHONY : src/tests/opencv_inc.s

# target to generate assembly for a file
src/tests/opencv_inc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin/tests/OpenCVInc.dir/build.make CMakeFiles/bin/tests/OpenCVInc.dir/src/tests/opencv_inc.cpp.s
.PHONY : src/tests/opencv_inc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bin/tests/OpenCVFaceTrack"
	@echo "... bin/tests/OpenCVInc"
	@echo "... src/tests/opencv_facetrack.o"
	@echo "... src/tests/opencv_facetrack.i"
	@echo "... src/tests/opencv_facetrack.s"
	@echo "... src/tests/opencv_inc.o"
	@echo "... src/tests/opencv_inc.i"
	@echo "... src/tests/opencv_inc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

